In [1]:
# 导入需要的包
import numpy as np
import pandas as pd

In [2]:
# 加载数据
data = pd.read_csv('data/msft_stockprices_dataset.csv')
print(data.shape)
data.head()

(1009, 6)


Date  High Price  Low Price  Open Price  Close Price  \
0  2014-09-09 00:00:00   46.970001  46.419998   46.470001    46.759998   
1  2014-09-10 00:00:00   46.939999  46.279999   46.820000    46.840000   
2  2014-09-11 00:00:00   47.000000  46.470001   46.740002    47.000000   
3  2014-09-12 00:00:00   47.020000  46.599998   46.910000    46.700001   
4  2014-09-15 00:00:00   46.709999  46.099998   46.540001    46.240002   

       Volume  
0  40302400.0  
1  27302400.0  
2  29216400.0  
3  38244700.0  
4  37667600.0

In [3]:
# 处理数据
from sklearn.preprocessing import StandardScaler
data_dealed = data.drop(columns = ['Date'])
# X = data.drop(columns = ['Date', 'Close Price'])
# y = data['Close Price']
scaler = StandardScaler().fit(data_dealed)
data_dealed = scaler.transform(data_dealed) 
X = data_dealed[:, [0, 1, 2, 4]]
y = data_dealed[:, 3]
print(X)
print(y)

[[-0.91598284 -0.90391509 -0.92084597  0.68249084]
 [-0.91755441 -0.91136232 -0.90239489 -0.17003453]
 [-0.91441148 -0.90125519 -0.9066122  -0.04451656]
 ...
 [ 2.33268529  2.34575113  2.33604607 -0.42086061]
 [ 2.3185426   2.33085667  2.33499189 -0.48506233]
 [ 2.36673301  2.39096657  2.36714924 -0.60118284]]
[-0.90778719 -0.90356623 -0.89512451 ...  2.36232771  2.33436455
  2.39609459]


In [4]:
# 划分数据集 训练集 测试集
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [5]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression(fit_intercept=True)

In [6]:
lr.fit(X_train, y_train)

/Users/zhang/.virtualenvs/ml_sklearn/lib/python3.6/site-packages/sklearn/linear_model/base.py:485: RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
  linalg.lstsq(X, y)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [7]:
y_pred = lr.predict(X_test)
y_pred

array([ 5.25249287e-02,  4.54259937e-02,  4.72689691e-01, -3.27057025e-01,
       -5.83716790e-01,  8.27646341e-02,  6.20998577e-02, -3.33363024e-01,
       -4.44470437e-01, -9.63480091e-01,  1.02450321e+00, -6.13804687e-01,
        2.38871938e+00, -6.81538381e-01, -1.15325157e+00,  5.74367376e-01,
        5.63463516e-01,  2.28355840e+00, -5.43123644e-01, -1.19027272e+00,
        2.54906887e+00,  2.44375533e+00, -9.65457199e-01, -8.82025881e-01,
       -8.92490132e-02, -8.72366281e-01, -5.94648605e-01, -5.27993737e-01,
       -5.16036443e-01,  1.61860019e+00,  1.48026606e+00,  1.51613824e+00,
       -1.14401761e+00, -1.07521256e+00,  4.39859908e-01, -8.43550063e-01,
        1.41416076e+00, -1.00297376e+00, -1.06748684e+00, -8.45170498e-01,
       -3.06195470e-01, -3.55190602e-01, -4.36762380e-01,  2.19639105e+00,
       -4.44085016e-01, -4.86289144e-01, -5.53415958e-01,  1.69479842e+00,
        1.01870580e+00,  1.40635569e+00, -1.90172610e-03,  5.25085907e-01,
       -8.14280741e-01,  

In [8]:
# 计算误差
ErrorTolerance = 0.006
error = np.abs(y_test - y_pred) / y_test 
error

array([ 2.80779472e-02,  1.56779452e-01,  6.22237566e-02, -8.64896555e-03,
       -2.22922843e-02,  1.01373723e-01,  9.56118465e-02, -3.47291537e-02,
       -7.51107745e-02, -1.95200138e-03,  1.05958316e-02, -2.17832028e-02,
        5.48688279e-03, -9.51893374e-03, -1.29866574e-02,  8.51903251e-03,
        1.15420344e-02,  1.79913104e-02, -3.30307223e-02, -8.67751885e-03,
        6.86459160e-03,  5.03973426e-04, -5.11082968e-03, -1.30189656e-03,
       -1.54102342e-01, -2.09100586e-02, -1.30276117e-02, -2.61199122e-02,
       -2.55928946e-03,  1.42937384e-03,  1.08631737e-02,  1.31071793e-02,
       -1.77128968e-02, -1.56133817e-02,  2.31329277e-02, -6.06210744e-03,
        2.05201799e-02, -2.24153780e-02, -1.23567914e-02, -5.22080817e-03,
       -1.33785059e-03, -6.43746049e-03, -2.44587481e-02,  5.43230814e-03,
       -3.20317186e-02, -1.89208412e-02, -1.09332272e-02,  2.58381795e-02,
        8.55137658e-03,  2.37683681e-02,  3.52218979e+00,  5.85226272e-03,
       -4.66087963e-03,  

In [9]:
# 输出精确率
true_count = np.sum(error <= ErrorTolerance)
print(true_count)
score = true_count / X_test.shape[0] * 100
print('accurency is {}% '.format(score))

152
accurency is 75.24752475247524% 


In [10]:
# 梯度下降
from sklearn.linear_model import SGDRegressor

In [11]:
# penalty='l2',alpha=0.0001 使用默认值
regressor = SGDRegressor(loss='squared_loss', max_iter=1000, tol=1e-3)

In [12]:
regressor.fit(X_train, y_train)
print('得分：', regressor.score(X_train, y_train))
print('回归系数：', regressor.coef_)
print('偏差：', regressor.intercept_ )

得分： 0.9992574166239304
回归系数： [ 0.3346538   0.33409278  0.3310011  -0.00086466]
偏差： [0.00053463]


In [13]:
print('得分：', regressor.score(X_test, y_test))

得分： 0.9993252111014893


In [24]:
y_pred_sgd = regressor.predict(X_test)

data_pred = np.insert(X_test, 3, values=y_pred_sgd, axis=1)
# data_pred
y_pred_sgd = scaler.inverse_transform(data_pred)
print(y_pred_sgd[:, 3])

[ 64.58059418  64.97449389  73.32710108  57.90340439  52.56919413
  65.45714451  65.47259795  57.37250159  55.54910472  45.33910426
  83.98075891  51.5330001  109.32719905  50.88508213  42.16307829
  74.57284379  74.30462641 107.59948746  53.58706816  41.55736505
 111.94620054 110.1211354   45.71501896  47.04139393  62.54849766
  47.46635054  52.24541445  53.99987774  54.02087436  94.67283193
  89.47295792  92.58499838  42.64689335  43.3919448   71.91122085
  48.27465195  91.16396067  44.86534691  43.61714762  47.53976717
  58.03841716  57.64369143  55.92777829 106.51387793  55.72458658
  54.38312296  53.07980473  96.04498437  83.63608325  90.30200857
  64.06177535  73.71140724  48.74398655  64.16667115  60.38548688
  72.60887946  53.02632118  47.83078623  45.23920965  44.5478935
  93.213838    50.46696216  46.80712449  65.23596343  94.70506684
  58.03050975  49.90368466  45.86286107  57.32707362  96.75598025
  42.53930713  45.86875167  50.59144619  47.56208205  73.65749916
  57.775969